package org.lwjgl.vulkan.enums;

import org.lwjgl.vulkan.VK10;
import org.lwjgl.vulkan.VK11;
import org.lwjgl.vulkan.VK12;
import org.lwjgl.vulkan.VK13;
import org.lwjgl.vulkan.KHRSwapchain;
import org.lwjgl.vulkan.KHRVideoDecodeQueue;
import org.lwjgl.vulkan.KHRSharedPresentableImage;
import org.lwjgl.vulkan.EXTFragmentDensityMap;
import org.lwjgl.vulkan.KHRFragmentShadingRate;
import org.lwjgl.vulkan.KHRVideoEncodeQueue;
import org.lwjgl.vulkan.EXTAttachmentFeedbackLoopLayout;
import org.lwjgl.vulkan.KHRMaintenance2;
import org.lwjgl.vulkan.NVShadingRateImage;
import org.lwjgl.vulkan.KHRSeparateDepthStencilLayouts;
import org.lwjgl.vulkan.KHRSynchronization2;


public enum VkImageLayout {
    VK_IMAGE_LAYOUT_UNDEFINED(VK10.VK_IMAGE_LAYOUT_UNDEFINED),
    VK_IMAGE_LAYOUT_GENERAL(VK10.VK_IMAGE_LAYOUT_GENERAL),
    VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL(VK10.VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL),
    VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL(VK10.VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL),
    VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL(VK10.VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL),
    VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL(VK10.VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL),
    VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL(VK10.VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL),
    VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL(VK10.VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL),
    VK_IMAGE_LAYOUT_PREINITIALIZED(VK10.VK_IMAGE_LAYOUT_PREINITIALIZED),
    VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL(VK11.VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL),
    VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL(VK11.VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL),
    VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL(VK12.VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL),
    VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL(VK12.VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL),
    VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL(VK12.VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL),
    VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL(VK12.VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL),
    VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL(VK13.VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL),
    VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL(VK13.VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL),
    VK_IMAGE_LAYOUT_PRESENT_SRC_KHR(KHRSwapchain.VK_IMAGE_LAYOUT_PRESENT_SRC_KHR),
    VK_IMAGE_LAYOUT_VIDEO_DECODE_DST_KHR(KHRVideoDecodeQueue.VK_IMAGE_LAYOUT_VIDEO_DECODE_DST_KHR),
    VK_IMAGE_LAYOUT_VIDEO_DECODE_SRC_KHR(KHRVideoDecodeQueue.VK_IMAGE_LAYOUT_VIDEO_DECODE_SRC_KHR),
    VK_IMAGE_LAYOUT_VIDEO_DECODE_DPB_KHR(KHRVideoDecodeQueue.VK_IMAGE_LAYOUT_VIDEO_DECODE_DPB_KHR),
    VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR(KHRSharedPresentableImage.VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR),
    VK_IMAGE_LAYOUT_FRAGMENT_DENSITY_MAP_OPTIMAL_EXT(EXTFragmentDensityMap.VK_IMAGE_LAYOUT_FRAGMENT_DENSITY_MAP_OPTIMAL_EXT),
    VK_IMAGE_LAYOUT_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR(KHRFragmentShadingRate.VK_IMAGE_LAYOUT_FRAGMENT_SHADING_RATE_ATTACHMENT_OPTIMAL_KHR),
    VK_IMAGE_LAYOUT_VIDEO_ENCODE_DST_KHR(KHRVideoEncodeQueue.VK_IMAGE_LAYOUT_VIDEO_ENCODE_DST_KHR),
    VK_IMAGE_LAYOUT_VIDEO_ENCODE_SRC_KHR(KHRVideoEncodeQueue.VK_IMAGE_LAYOUT_VIDEO_ENCODE_SRC_KHR),
    VK_IMAGE_LAYOUT_VIDEO_ENCODE_DPB_KHR(KHRVideoEncodeQueue.VK_IMAGE_LAYOUT_VIDEO_ENCODE_DPB_KHR),
    VK_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT(EXTAttachmentFeedbackLoopLayout.VK_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXT),
    VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR(KHRMaintenance2.VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR),
    VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR(KHRMaintenance2.VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR),
    VK_IMAGE_LAYOUT_SHADING_RATE_OPTIMAL_NV(NVShadingRateImage.VK_IMAGE_LAYOUT_SHADING_RATE_OPTIMAL_NV),
    VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL_KHR(KHRSeparateDepthStencilLayouts.VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_OPTIMAL_KHR),
    VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL_KHR(KHRSeparateDepthStencilLayouts.VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_OPTIMAL_KHR),
    VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL_KHR(KHRSeparateDepthStencilLayouts.VK_IMAGE_LAYOUT_STENCIL_ATTACHMENT_OPTIMAL_KHR),
    VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL_KHR(KHRSeparateDepthStencilLayouts.VK_IMAGE_LAYOUT_STENCIL_READ_ONLY_OPTIMAL_KHR),
    VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL_KHR(KHRSynchronization2.VK_IMAGE_LAYOUT_READ_ONLY_OPTIMAL_KHR),
    VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL_KHR(KHRSynchronization2.VK_IMAGE_LAYOUT_ATTACHMENT_OPTIMAL_KHR);

    private final int value;

    VkImageLayout(int value) {
        this.value = value;
    }

    public int getValue() {
        return this.value;
    }

    public static VkImageLayout of(int value) {
        for (VkImageLayout mode : values()) {
            if(mode.value == value) {
                return mode;
            }
        }
        throw new IllegalStateException("Unexpected value: " + value);
    }
}
